# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
