# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170526_0300'),
    ]

    operations = [
    ]
